<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260704203311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create library_member table.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('library_member')) {
            $this->addSql('CREATE TABLE library_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identification_number INT NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_library_member_identification_number ON library_member (identification_number)');
        }
    }

    public function down(Schema $schema): void
    {
        if ($schema->hasTable('library_member')) {
            $this->addSql('DROP TABLE library_member');
        }
    }
}
