<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703134318 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create boot table.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('book')) {
            $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number INT NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_book_serial_number ON book (serial_number)');
        }

        if (!$schema->hasTable('messenger_messages')) {
            $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        }
    }

    public function down(Schema $schema): void
    {
        if ($schema->hasTable('book')) {
            $this->addSql('DROP TABLE book');
        }
        if ($schema->hasTable('messenger_messages')) {
            $this->addSql('DROP TABLE messenger_messages');
        }
    }
}
